---
title: "District and Personal Wealth in Congress"
author: "Darrian Stacy"
date: '2022-06-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, load ACS 5 year estimate data}

#info on comparing data over time: #https://www.census.gov/data/developers/data-sets/acs-5year.html
#info on tidycensus
#https://walker-data.com/tidycensus/

library(tidyverse)
library(tidycensus)

census_api_key("68432a7c59eb07fe808c5f1dd299beee2ec5c765")

vars <- paste0("B19326_001", "B19013_001", "B17001_001")#median income over past 12 months (individual), median household income, poverty status

acs5 <- load_variables(2009, "acs5", cache = TRUE)
acs5_2 <- load_variables(2014, "acs5", cache = TRUE)

acs05_09 <- get_acs(geography = "congressional district",
        variables = c(estimate = "B19013_001"),
        year = 2009,
        moe_level = 95)

acs10_14 <- get_acs(geography = "congressional district",
        variables = c(estimate = "B19013_001"),
        year = 2014,
        moe_level = 95)

rm(acs5, acs5_2)

###Poverty
acs05_09t <- get_acs(geography = "congressional district",
        variables = c(total = "B17001_001"),
        year = 2009,
        moe_level = 95) #must first get total pop

acs05_09p <- get_acs(geography = "congressional district",
        variables = c(poverty = "B17001_002"),
        year = 2009,
        moe_level = 95) #then calculate pct. poverty from total pop after joining dat

acs05_09pt <- cbind(acs05_09p, acs05_09t[,3:5]) #join and subset to relevant columns

colnames(acs05_09pt) <- c('GEOID', 'NAME', 
                           'variable1', 'poverty', 'poverty_moe',
                           'variable2', 'total', 'total_moe')

acs05_09pt <- acs05_09pt %>%
  group_by(NAME) %>%
  summarize(poverty_pct = poverty/total,
            poverty_pct_moe = moe_prop(num = poverty, denom = total, 
                           moe_num = poverty_moe, moe_denom = total_moe)) 


#Poverty 2010-2014
acs10_14t <- get_acs(geography = "congressional district",
        variables = c(total = "B17001_001"),
        year = 2014,
        moe_level = 95) #must first get total pop

acs10_14p <- get_acs(geography = "congressional district",
        variables = c(poverty = "B17001_002"),
        year = 2014,
        moe_level = 95) #then calculate pct. poverty from total pop after joining dat

acs10_14pt <- cbind(acs10_14p, acs10_14t[,3:5]) #join and subset to relevant columns

colnames(acs10_14pt) <- c('GEOID', 'NAME', 
                           'variable1', 'poverty', 'poverty_moe',
                           'variable2', 'total', 'total_moe')

acs10_14pt <- acs10_14pt %>%
  group_by(NAME) %>%
  summarize(poverty_pct = poverty/total,
            poverty_pct_moe = moe_prop(num = poverty, denom = total, 
                           moe_num = poverty_moe, moe_denom = total_moe)) 

#gini index for latter years

acs10_14g <- get_acs(geography = "congressional district",
        variables = c(gini = "B19083_001"),
        year = 2014,
        moe_level = 95) # range from 0-1 associated with increasing inequality

colnames(acs10_14g) <- c('GEOID', 'NAME', 
                           'variable', 'gini', 'gini_moe')

#merge in all variables

acs05_09 <- merge(acs05_09, acs05_09pt, by = "NAME")
acs10_14 <- merge(acs10_14, acs10_14pt, by = "NAME")

#acs10_14 <- merge(acs10_14, acs10_14g, by = "NAME") #for gini

rm(acs05_09p, acs05_09t, acs10_14p, acs10_14t, acs05_09pt, acs10_14pt, acs10_14g)
```

```{r, acs adjust median income for inflation}

library("blscrapeR")

df09 <- inflation_adjust(2009)
df09 <- df09[df09$year == 2009 | df09$year==2021,] #Scrape the cpi and new value

df14 <- inflation_adjust(2014)
df14 <- df14[df14$year == 2014 | df14$year==2021,]


cpi <- rbind(df09[,1:2],df14[1,1:2])

rm(df09,df14)


#construct avg. worth adjusted in 2021 dollars: ((median income*2021 cpi)/old cpi)
acs05_09$cd_median_income <- ((acs05_09$estimate*270.9654)/214.5647)
acs05_09$cd_median_income_moe <- ((acs05_09$moe*270.9654)/214.5647)

acs10_14$cd_median_income <- ((acs10_14$estimate*270.9654)/236.7150)
acs10_14$cd_median_income_moe <- ((acs10_14$moe*270.9654)/236.7150)



rm(cpi)

```


```{r, clean mbr wealth data (open secrets)}
library(ggplot2)

#Assets
library(readr)
assets <- read_csv("assets.csv")

#delete duplicates
assets$Dupe1[assets$Dupe1 == 'd' | assets$Dupe1 == 'D'] <- 1
assets$Dupe2[assets$Dupe2 == 'D' | assets$Dupe2 == 'd'] <- 1

assets$Dupe1[assets$Dupe1 == ',' | is.na(assets$Dupe1)] <- 0
assets$Dupe2[assets$Dupe2 == ',' | is.na(assets$Dupe2)] <- 0


assets$Dupe1 <- as.numeric(as.character(assets$Dupe1))
assets$Dupe2 <- as.numeric(as.character(assets$Dupe2))

assets <- subset(assets, Dupe1 == 0 & Dupe2 == 0 ) # starts w/ 440,921 & drops 67,763 duplicates

#Clean up Exact Values of assets
assets$AssetExactValue <- gsub( ',', '', assets$AssetExactValue) #replace ","
assets$AssetExactValue[assets$AssetExactValue == ""] <-NA
assets$AssetExactValue[assets$AssetExactValue == "Tax-Deferred"] <-NA
assets$AssetExactValue[assets$AssetExactValue == "R"] <-NA
assets$AssetExactValue[assets$AssetExactValue == "r"] <-NA
assets$AssetExactValue[assets$AssetExactValue == "m"] <-NA
assets$AssetExactValue[assets$AssetExactValue == "k"] <-NA
assets$AssetExactValue[assets$AssetExactValue == "l"] <-NA
assets$AssetExactValue[assets$AssetExactValue == "f"] <-NA
assets$AssetExactValue[assets$AssetExactValue == "|"] <-NA
assets$AssetExactValue <- as.numeric(as.character(assets$AssetExactValue))

  ##convert NAs to 0 and add a dummy when assets have exact values 
assets$AssetExactValue[is.na(assets$AssetExactValue)] <-0
assets$Exact <- NA
assets$Exact <- ifelse(assets$AssetExactValue > 0, 1, 0)


#Then, we separate House and Senate assets
hassets <- subset(assets, Chamber =="H" | Chamber == "h")
sassets <- subset(assets, Chamber =="S" | Chamber == "s")

#Then, we create new columns for the min and max asset values based on the coding
  
  ##H min assets
hassets$minvalue <- NA
hassets$minvalue[hassets$AssetValue =="A"]<- 0
hassets$minvalue[hassets$AssetValue =="B"]<- 1
hassets$minvalue[hassets$AssetValue =="C"]<- 1001
hassets$minvalue[hassets$AssetValue =="D"]<- 15001
hassets$minvalue[hassets$AssetValue =="E"]<- 50001
hassets$minvalue[hassets$AssetValue =="F"]<- 100001
hassets$minvalue[hassets$AssetValue =="G"]<- 250001
hassets$minvalue[hassets$AssetValue =="H"]<- 500001
hassets$minvalue[hassets$AssetValue =="I"]<- 1000001
hassets$minvalue[hassets$AssetValue =="J"]<- 5000001
hassets$minvalue[hassets$AssetValue =="K"]<- 25000001
hassets$minvalue[hassets$AssetValue =="L"]<- 50000001
hassets$minvalue <- ifelse(hassets$Exact == 1, hassets$AssetExactValue, hassets$minvalue)#if there is an exact value of asset include, if not just print the min value 


  ##H max assets
hassets$maxvalue <- NA
hassets$maxvalue[hassets$AssetValue =="A"]<- 0
hassets$maxvalue[hassets$AssetValue =="B"]<- 1000
hassets$maxvalue[hassets$AssetValue =="C"]<- 15000
hassets$maxvalue[hassets$AssetValue =="D"]<- 50000
hassets$maxvalue[hassets$AssetValue =="E"]<- 100000
hassets$maxvalue[hassets$AssetValue =="F"]<- 250000
hassets$maxvalue[hassets$AssetValue =="G"]<- 500000
hassets$maxvalue[hassets$AssetValue =="H"]<- 1000000
hassets$maxvalue[hassets$AssetValue =="I"]<- 5000000
hassets$maxvalue[hassets$AssetValue =="J"]<- 25000000
hassets$maxvalue[hassets$AssetValue =="K"]<- 50000000
hassets$maxvalue[hassets$AssetValue =="L"]<- 50000001
hassets$maxvalue <- ifelse(hassets$Exact == 1, hassets$AssetExactValue, hassets$maxvalue)#if there is an exact value of asset include, if not just print the max value 

  ##S min assets
sassets$minvalue <- NA
sassets$minvalue[sassets$AssetValue =="A"]<- 0
sassets$minvalue[sassets$AssetValue =="B"]<- 1001
sassets$minvalue[sassets$AssetValue =="C"]<- 15001
sassets$minvalue[sassets$AssetValue =="D"]<- 50001
sassets$minvalue[sassets$AssetValue =="E"]<- 100001
sassets$minvalue[sassets$AssetValue =="F"]<- 250001
sassets$minvalue[sassets$AssetValue =="G"]<- 500001
sassets$minvalue[sassets$AssetValue =="H"]<- 1000001
sassets$minvalue[sassets$AssetValue =="I"]<- 1000001 #duplicates in coding for some reason
sassets$minvalue[sassets$AssetValue =="J"]<- 5000001
sassets$minvalue[sassets$AssetValue =="K"]<- 25000001
sassets$minvalue[sassets$AssetValue =="L"]<- 50000001
sassets$minvalue <- ifelse(sassets$Exact == 1, sassets$AssetExactValue, sassets$minvalue)#if there is an exact value of asset include, if not just print the min value 


  ##S max assets
sassets$maxvalue <- NA
sassets$maxvalue[sassets$AssetValue =="A"]<- 1000
sassets$maxvalue[sassets$AssetValue =="B"]<- 15000
sassets$maxvalue[sassets$AssetValue =="C"]<- 50000
sassets$maxvalue[sassets$AssetValue =="D"]<- 100000
sassets$maxvalue[sassets$AssetValue =="E"]<- 250000
sassets$maxvalue[sassets$AssetValue =="F"]<- 500000
sassets$maxvalue[sassets$AssetValue =="G"]<- 1000000
sassets$maxvalue[sassets$AssetValue =="H"]<- 1000001
sassets$maxvalue[sassets$AssetValue =="I"]<- 5000000
sassets$maxvalue[sassets$AssetValue =="J"]<- 25000000
sassets$maxvalue[sassets$AssetValue =="K"]<- 50000000
sassets$maxvalue[sassets$AssetValue =="L"]<- 50000001
sassets$maxvalue <- ifelse(sassets$Exact == 1, sassets$AssetExactValue, sassets$maxvalue)#if there is an exact value of asset include, if not just print the max value 

rm(assets)

h_mbr_assets <- aggregate(cbind(minvalue, maxvalue) ~ CID + CalendarYear, data = hassets, sum)


#Merge in legislator identification
#https://github.com/unitedstates/congress-legislators
legislators_historical <- read_csv("legislators-historical.csv")
legislators_current <- read_csv("legislators-current.csv.csv")
legislators <- rbind(legislators_historical, legislators_current)


house <- merge(h_mbr_assets, legislators, by.x = c("CID"), by.y = c("opensecrets_id")) #Does not match info for 1 yr of David Rivera, 6 years of Tom Marino, and 1 yr of an unidentified mbr.

rm(h_mbr_assets, hassets)

################



#Aggregate Senate assets and liabiliies by mbr and year
s_mbr_assets <- aggregate(cbind(minvalue, maxvalue) ~ CID + CalendarYear, data = sassets, sum)

senate <- merge(s_mbr_assets, legislators, by.x = c("CID"), by.y = c("opensecrets_id"))

rm(legislators, legislators_current, legislators_historical, s_mbr_assets, sassets)


#Create the avg. assets variable
library(dplyr)
house <- house %>% mutate(assets_mean = (minvalue + maxvalue)/2) #avg assets

####
senate <- senate %>% mutate(assets_mean = (minvalue + maxvalue)/2)


#Add in congress and year variables
house$congress <- NA
house$congress[house$CalendarYear == "4"] <- 108
house$congress[house$CalendarYear == "5" | house$CalendarYear == "6"] <- 109
house$congress[house$CalendarYear == "7" | house$CalendarYear == "8"] <- 110
house$congress[house$CalendarYear == "9" | house$CalendarYear == "10"] <- 111
house$congress[house$CalendarYear == "11"| house$CalendarYear == "12" ] <- 112
house$congress[house$CalendarYear == "13"| house$CalendarYear == "14"] <- 113



senate$congress <- NA
senate$congress[senate$CalendarYear == "4"] <- 108
senate$congress[senate$CalendarYear == "5" | senate$CalendarYear == "6"] <- 109
senate$congress[senate$CalendarYear == "7" | senate$CalendarYear == "8"] <- 110
senate$congress[senate$CalendarYear == "9" | senate$CalendarYear == "10"] <- 111
senate$congress[senate$CalendarYear == "11"| senate$CalendarYear == "12" ] <- 112
senate$congress[senate$CalendarYear == "13"| senate$CalendarYear == "14"] <- 113


house$year <- NA
house$year[house$CalendarYear == "4"] <- 2004
house$year[house$CalendarYear == "5"] <- 2005
house$year[house$CalendarYear == "6"] <- 2006
house$year[house$CalendarYear == "7"] <- 2007
house$year[house$CalendarYear == "8"] <- 2008
house$year[house$CalendarYear == "9"] <- 2009
house$year[house$CalendarYear == "10"] <- 2010
house$year[house$CalendarYear == "11"] <- 2011
house$year[house$CalendarYear == "12"] <- 2012
house$year[house$CalendarYear == "13"] <- 2013
house$year[house$CalendarYear == "14"] <- 2014



senate$year <- NA
senate$year[senate$CalendarYear == "4"] <- 2004
senate$year[senate$CalendarYear == "5"] <- 2005
senate$year[senate$CalendarYear == "6"] <- 2006
senate$year[senate$CalendarYear == "7"] <- 2007
senate$year[senate$CalendarYear == "8"] <- 2008
senate$year[senate$CalendarYear == "9"] <- 2009
senate$year[senate$CalendarYear == "10"] <- 2010
senate$year[senate$CalendarYear == "11"] <- 2011
senate$year[senate$CalendarYear == "12"] <- 2012
senate$year[senate$CalendarYear == "13"] <- 2013
senate$year[senate$CalendarYear == "14"] <- 2014

#Add wealth quintiles

house <- house %>%
  group_by(icpsr_id, congress) %>%
  summarise(assets_mean_c = mean(assets_mean))   #average two years together for each congress
      ####STOP and REMEMBER TO FIND those with missing icpsrs in this data

library(dplyr)
list2env(split(house, house$congress), envir = .GlobalEnv)

`108`$quintile <- as.factor(ntile(`108`$assets_mean_c, 5))
`109`$quintile <- as.factor(ntile(`109`$assets_mean_c, 5))
`110`$quintile <- as.factor(ntile(`110`$assets_mean_c, 5))
`111`$quintile <- as.factor(ntile(`111`$assets_mean_c, 5))
`112`$quintile <- as.factor(ntile(`112`$assets_mean_c, 5))
`113`$quintile <- as.factor(ntile(`113`$assets_mean_c, 5))

house <- rbind(`108`, `109`, `110`, `111`, `112`, `113`)




list2env(split(senate, senate$year), envir = .GlobalEnv)

`2004`$quintile <- as.factor(ntile(`2004`$assets_mean, 5))
`2005`$quintile <- as.factor(ntile(`2005`$assets_mean, 5))
`2006`$quintile <- as.factor(ntile(`2006`$assets_mean, 5))
`2007`$quintile <- as.factor(ntile(`2007`$assets_mean, 5))
`2008`$quintile <- as.factor(ntile(`2008`$assets_mean, 5))
`2009`$quintile <- as.factor(ntile(`2009`$assets_mean, 5))
`2010`$quintile <- as.factor(ntile(`2010`$assets_mean, 5))
`2011`$quintile <- as.factor(ntile(`2011`$assets_mean, 5))
`2012`$quintile <- as.factor(ntile(`2012`$assets_mean, 5))
`2013`$quintile <- as.factor(ntile(`2013`$assets_mean, 5))
`2014`$quintile <- as.factor(ntile(`2014`$assets_mean, 5))

senate <- rbind(`2004`,
                `2005`,`2006`,
                `2007`,`2008`,
                `2009`,`2010`,
                `2011`,`2012`,
                `2013`,`2014`)

rm(`2004`,`2005`,`2006`,`2007`,`2008`,`2009`,`2010`,`2011`,`2012`,`2013`,`2014`)
rm(`108`, `109`, `110`, `111`, `112`, `113`)
```


```{r, merge acs and congress wealth data}

#use CEL data as a bridge between acs and wealth data

cel <- read.csv("voldenwisemanJOPsenate.csv")

#subset to relevant congresses/Houses (108th: 2003-2005; 110th: 2007-2009 & 11th: 2009-2011; 113th: 2013-2015)
cel_108_110 <- cel[cel$congress >= 108 & cel$congress <= 110 & cel$house == 1,]
cel_111_113 <- cel[cel$congress >= 111 & cel$congress <= 113 & cel$house == 1,] 
  
rm(cel)

acs05_09$cd <- as.numeric(substr(acs05_09$NAME, 24, 25)) #create cd var

acs05_09$state <- substring(acs05_09$NAME, regexpr(",", acs05_09$NAME) + 2)

acs05_09$st_name <- ifelse(acs05_09$state == "Alabama", "AL",
                           ifelse(acs05_09$state == "Arizona", "AZ",
                                  ifelse(acs05_09$state == "Arkansas", "AR",
                                         ifelse(acs05_09$state == "California", "CA",
                                                ifelse(acs05_09$state == "Colorado", "CO",
                                                       ifelse(acs05_09$state == "Connecticut", "CT",
                                                              ifelse(acs05_09$state == "Delaware", "DE",
                                                                     ifelse(acs05_09$state == "District of Columbia", "DC",
                                                                            ifelse(acs05_09$state == "Florida", "FL",
                                                                                   ifelse(acs05_09$state == "Georgia", "GA",
                                                                                          ifelse(acs05_09$state == "Hawaii", "HI",
                                                                                                 ifelse(acs05_09$state == "Idaho", "ID",
                                                                                                        ifelse(acs05_09$state == "Illinois", "IL",
                                                                                                               ifelse(acs05_09$state == "Indiana", "IN",
                                                                                                                      ifelse(acs05_09$state == "Iowa", "IA",
                                                                                                                             ifelse(acs05_09$state == "Kansas",  "KS",
                                                                                                                                    ifelse(acs05_09$state == "Kentucky", "KY",
                                                                                                                                           ifelse(acs05_09$state == "Louisiana", "LA",
                                                                                                                                                  ifelse(acs05_09$state == "Maine", "ME",
                                                                                                                                                         ifelse(acs05_09$state == "Maryland", "MD",
                                                                                                                                                                ifelse(acs05_09$state == "Massachusetts", "MA",
                                                                                                                                                                       ifelse(acs05_09$state == "Michigan", "MI",
                                                                                                                                                                              ifelse(acs05_09$state == "Minnesota", "MN",
                                                                                                                                                                                     ifelse(acs05_09$state == "Mississippi", "MS",
                                                                                                                                                                                            ifelse(acs05_09$state == "Missouri", "MO",
                                                                                                                                                                                                   ifelse(acs05_09$state == "Montana", "MT",
                                                                                                                                                                                                          ifelse(acs05_09$state == "Nebraska", "NE",
                                                                                                                                                                                                                 ifelse(acs05_09$state == "Nevada", "NV",
                                                                                                                                                                                                                        ifelse(acs05_09$state == "New Hampshire", "NH",
                                                                                                                                                                                                                               ifelse(acs05_09$state == "New Jersey", "NJ",
                                                                                                                                                                                                                                      ifelse(acs05_09$state == "New Mexico", "NM",
                                                                                                                                                                                                                                             ifelse(acs05_09$state == "New York", "NY",
                                                                                                                                                                                                                                                    ifelse(acs05_09$state == "North Carolina", "NC",
                                                                                                                                                                                                                                                           ifelse(acs05_09$state == "North Dakota", "ND",
                                                                                                                                                                                                                                                                  ifelse(acs05_09$state == "Ohio", "OH",
                                                                                                                                                                                                                                                                         ifelse(acs05_09$state == "Oklahoma", "OK",
                                                                                                                                                                                                                                                                                ifelse(acs05_09$state == "Oregon", "OR",
                                                                                                                                                                                                                                                                                       ifelse(acs05_09$state == "Pennsylvania", "PA",
                                                                                                                                                                                                                                                                                              ifelse(acs05_09$state == "Rhode Island", "RI",
                                                                                                                                                                                                                                                                                                     ifelse(acs05_09$state == "South Carolina", "SC",
                                                                                                                                                                                                                                                                                                            ifelse(acs05_09$state == "South Dakota", "SD",
                                                                                                                                                                                                                                                                                                                   ifelse(acs05_09$state == "Tennessee", "TN",
                                                                                                                                                                                                                                                                                                                          ifelse(acs05_09$state == "Texas", "TX",
                                                                                                                                                                                                                                                                                                                                 ifelse(acs05_09$state == "Utah", "UT",
                                                                                                                                                                                                                                                                                                                                        ifelse(acs05_09$state == "Vermont", "VT",
                                                                                                                                                                                                                                                                                                                                               ifelse(acs05_09$state == "Virginia", "VA",
                                                                                                                                                                                                                                                                                                                                                      ifelse(acs05_09$state == "Washington", "WA",
                                                                                                                                                                                                                                                                                                                                                             ifelse(acs05_09$state == "West Virginia", "WV",
                                                                                                                                                                                                                                                                                                                                                                    ifelse(acs05_09$state == "Wisconsin", "WI",
                                                                                                                                                                                                                                                                                                                                                                           ifelse(acs05_09$state == "Wyoming", "WY", NA))))))))))))))))))))))))))))))))))))))))))))))))))


acs05_09$st_name <- ifelse(acs05_09$state == "Puerto Rico", "PR",
                           ifelse(acs05_09$state == "Alaska", "AK", acs05_09$st_name))

acs05_09$cd[is.na(acs05_09$cd)] <- 1


#Run the same code for acs10_14

acs10_14$cd <- as.numeric(substr(acs10_14$NAME, 24, 25)) #create cd var

acs10_14$state <- substring(acs10_14$NAME, regexpr(",", acs10_14$NAME) + 2)

acs10_14$st_name <- ifelse(acs10_14$state == "Alabama", "AL",
                           ifelse(acs10_14$state == "Arizona", "AZ",
                                  ifelse(acs10_14$state == "Arkansas", "AR",
                                         ifelse(acs10_14$state == "California", "CA",
                                                ifelse(acs10_14$state == "Colorado", "CO",
                                                       ifelse(acs10_14$state == "Connecticut", "CT",
                                                              ifelse(acs10_14$state == "Delaware", "DE",
                                                                     ifelse(acs10_14$state == "District of Columbia", "DC",
                                                                            ifelse(acs10_14$state == "Florida", "FL",
                                                                                   ifelse(acs10_14$state == "Georgia", "GA",
                                                                                          ifelse(acs10_14$state == "Hawaii", "HI",
                                                                                                 ifelse(acs10_14$state == "Idaho", "ID",
                                                                                                        ifelse(acs10_14$state == "Illinois", "IL",
                                                                                                               ifelse(acs10_14$state == "Indiana", "IN",
                                                                                                                      ifelse(acs10_14$state == "Iowa", "IA",
                                                                                                                             ifelse(acs10_14$state == "Kansas",  "KS",
                                                                                                                                    ifelse(acs10_14$state == "Kentucky", "KY",
                                                                                                                                           ifelse(acs10_14$state == "Louisiana", "LA",
                                                                                                                                                  ifelse(acs10_14$state == "Maine", "ME",
                                                                                                                                                         ifelse(acs10_14$state == "Maryland", "MD",
                                                                                                                                                                ifelse(acs10_14$state == "Massachusetts", "MA",
                                                                                                                                                                       ifelse(acs10_14$state == "Michigan", "MI",
                                                                                                                                                                              ifelse(acs10_14$state == "Minnesota", "MN",
                                                                                                                                                                                     ifelse(acs10_14$state == "Mississippi", "MS",
                                                                                                                                                                                            ifelse(acs10_14$state == "Missouri", "MO",
                                                                                                                                                                                                   ifelse(acs10_14$state == "Montana", "MT",
                                                                                                                                                                                                          ifelse(acs10_14$state == "Nebraska", "NE",
                                                                                                                                                                                                                 ifelse(acs10_14$state == "Nevada", "NV",
                                                                                                                                                                                                                        ifelse(acs10_14$state == "New Hampshire", "NH",
                                                                                                                                                                                                                               ifelse(acs10_14$state == "New Jersey", "NJ",
                                                                                                                                                                                                                                      ifelse(acs10_14$state == "New Mexico", "NM",
                                                                                                                                                                                                                                             ifelse(acs10_14$state == "New York", "NY",
                                                                                                                                                                                                                                                    ifelse(acs10_14$state == "North Carolina", "NC",
                                                                                                                                                                                                                                                           ifelse(acs10_14$state == "North Dakota", "ND",
                                                                                                                                                                                                                                                                  ifelse(acs10_14$state == "Ohio", "OH",
                                                                                                                                                                                                                                                                         ifelse(acs10_14$state == "Oklahoma", "OK",
                                                                                                                                                                                                                                                                                ifelse(acs10_14$state == "Oregon", "OR",
                                                                                                                                                                                                                                                                                       ifelse(acs10_14$state == "Pennsylvania", "PA",
                                                                                                                                                                                                                                                                                              ifelse(acs10_14$state == "Rhode Island", "RI",
                                                                                                                                                                                                                                                                                                     ifelse(acs10_14$state == "South Carolina", "SC",
                                                                                                                                                                                                                                                                                                            ifelse(acs10_14$state == "South Dakota", "SD",
                                                                                                                                                                                                                                                                                                                   ifelse(acs10_14$state == "Tennessee", "TN",
                                                                                                                                                                                                                                                                                                                          ifelse(acs10_14$state == "Texas", "TX",
                                                                                                                                                                                                                                                                                                                                 ifelse(acs10_14$state == "Utah", "UT",
                                                                                                                                                                                                                                                                                                                                        ifelse(acs10_14$state == "Vermont", "VT",
                                                                                                                                                                                                                                                                                                                                               ifelse(acs10_14$state == "Virginia", "VA",
                                                                                                                                                                                                                                                                                                                                                      ifelse(acs10_14$state == "Washington", "WA",
                                                                                                                                                                                                                                                                                                                                                             ifelse(acs10_14$state == "West Virginia", "WV",
                                                                                                                                                                                                                                                                                                                                                                    ifelse(acs10_14$state == "Wisconsin", "WI",
                                                                                                                                                                                                                                                                                                                                                                           ifelse(acs10_14$state == "Wyoming", "WY", NA))))))))))))))))))))))))))))))))))))))))))))))))))


acs10_14$st_name <- ifelse(acs10_14$state == "Puerto Rico", "PR",
                           ifelse(acs10_14$state == "Alaska", "AK", acs10_14$st_name))

acs10_14$cd[is.na(acs10_14$cd)] <- 1


cel_acs05_09 <- merge(cel_108_110, acs05_09, by = c("st_name", "cd")) #pennsylvania 5th missing for three congresses
cel_acs10_14 <- merge(cel_111_113, acs10_14, by = c("st_name", "cd"))

cel_acs05_14 <- rbind(cel_acs05_09, cel_acs10_14)

rm(cel_acs05_09, cel_acs10_14, cel_108_110, cel_111_113, acs05_09, acs10_14)

#now merge cel/acs with wealth data
house_merge <- na.omit(unique(house[,c("icpsr_id", "congress", "quintile")]))


cel_acs_os <- merge(cel_acs05_14, house_merge, 
                    by.x = c("icpsr", "congress"), by.y = c("icpsr_id", "congress")) #shortens data to by Congress

#cel_acs_os <- merge(cel_acs10_14, house_merge, 
                    #by.x = c("icpsr", "congress"), by.y = c("icpsr_id", "congress")) #for gini calc in two congresses

rm(cel_acs05_14, house_merge)
```


#three ideas: 
#1) Rich/Poor come from Rich/Poor districts



```{r, Do rich/poor members come from rich/poor districts}

#add in variables 


cel_acs_os$q1 <- ifelse(cel_acs_os$quintile==1, 1, 0)
cel_acs_os$q5 <- ifelse(cel_acs_os$quintile==5, 1, 0)

plot(factor(cel_acs_os$q1), cel_acs_os$poverty_pct*100)

cel_acs_os$female <- ifelse(cel_acs_os$majwomen == 1 | cel_acs_os$minwomen== 1, 1, 0)

cel_acs_os <- 
  cel_acs_os %>%
  group_by(cel_acs_os$congress, cel_acs_os$st_name) %>% 
  add_tally(name = "deleg_size")

summary(lm(log(cd_median_income) ~ q1 + q5 + seniority + factor(congress) + deleg_size  + st_name, cel_acs_os)) #wealthiest members come from slightly wealthier areas q5 has almost 2% higher median income nationwide, and 4.5% higher median income within states. There's no difference for q1.  
#need to understand why; do wealthier members run more or win more? This is also important for the elections chapter as a potential confounder.

summary(lm(q5 ~ log(cd_median_income) + seniority + factor(congress) + deleg_size + st_name + female, cel_acs_os))
#shows that 1% increase in cd median income is associated with a 5-16% increase in probability in a q5 rep. Holds most within states.

summary(lm(q1 ~ log(cd_median_income) + seniority + factor(congress) + deleg_size + st_name + female, cel_acs_os)) #higher income makes it less likely to have a q1 rep but not statistically significant.



#plots over time

income_plotdat <- cel_acs_os %>%
  group_by(congress,q1, q5) %>%
  summarise(mean_median_income = mean(cd_median_income, na.rm = TRUE)) %>%
  mutate(quintile = ifelse(q1 == 1, "Bottom 20%", 
                           ifelse(q5==1, "Top 20%", "Middle 60%")))

ggplot(data = income_plotdat, aes(x = congress, y = mean_median_income, color = quintile)) +
  geom_line() +
  theme_minimal()#top 20% appear to represent wealthier districts for 2/3 of Congresses. In 111th-112th Congresses,they represented poorer districts than bottom 20% members (why? retirements/replacements or changes in economy? Coincides with 14 changes in membership in House, and the start of the great recession)  

income_plotdat2 <- cel_acs_os %>%
  group_by(congress, q1) %>%
  summarise(mean_median_income = mean(cd_median_income, na.rm = TRUE,),
            mean_moe = mean(cd_median_income_moe, na.rm = TRUE)) %>%
  mutate(quintile = ifelse(q1==1, "Bottom 20%", "21-100%"))

ggplot(data = income_plotdat2, aes(x = congress, y = mean_median_income, color = quintile)) +
  geom_line() +
  geom_errorbar(aes(ymin = mean_median_income-mean_moe, ymax=mean_median_income+mean_moe),
                width = .05,
                alpha = .5 ) +
  theme_minimal() #just with q1 and everyone else. q1 median income generally below everywhere else, but higher during the two great recession congresses until crashing after.


income_plotdat3 <- cel_acs_os %>%
  group_by(congress, q5) %>%
  summarise(mean_median_income = mean(cd_median_income, na.rm = TRUE),
            mean_moe = mean(cd_median_income_moe, na.rm = TRUE)) %>%
  mutate(quintile = ifelse(q5==1, "Top 20%", "0-79.9%"))

ggplot(data = income_plotdat3, aes(x = congress, y = mean_median_income, color = quintile)) +
  geom_line() +
  geom_errorbar(aes(ymin = mean_median_income-mean_moe, ymax=mean_median_income+mean_moe),
                width = .05,
                alpha = .5 ) +
  theme_minimal() #just with q5 and everyone else. Shows that the wealthiest members represented districts that had higher household incomes except during the start of the great recession. Also shows that wealthier members' districts appeared to recover more quickly than others.

#Raises questions about whether these members were most effective at directing federal support to their districts 

#check within state
income_plotdat4 <- cel_acs_os[,c("icpsr","congress","st_name","cd","quintile","cd_median_income")] #within most states the wealthiest districts are represented by q5 members. Exceptions include A states.



#poverty stats

cel_acs_os$poverty_pct2 <- cel_acs_os$poverty_pct*100

summary(lm(poverty_pct ~ q1 + q5 + seniority + factor(congress) + deleg_size  + st_name, cel_acs_os)) #q5 has lower poverty. Being q5 rep is associated with a percentage point decline in poverty.

summary(lm(q1 ~ poverty_pct2 + seniority + factor(congress) + deleg_size + st_name + female, cel_acs_os)) #districts with more poverty more likely to have q1 member; percentage point increase in poverty associated with 0.5 pct point increase in likelihood of q1.

summary(lm(q5 ~ poverty_pct2 + seniority + factor(congress) + deleg_size + st_name + female, cel_acs_os)) #districts with more poverty less likely to have q5 member; percentage point increase in poverty associated with 0.8 pct point decrease in likelihood of q5.


poverty_plotdat <- cel_acs_os %>%
  group_by(congress, q1) %>%
  summarise(mean_poverty = mean(poverty_pct, na.rm = TRUE,),
            poverty_moe = mean(poverty_pct_moe, na.rm = TRUE)) %>%
  mutate(quintile = ifelse(q1==1, "Bottom 20%", "21-100%"))

ggplot(data = poverty_plotdat, aes(x = congress, y = mean_poverty, color = quintile)) +
  geom_line() +
  geom_errorbar(aes(ymin = mean_poverty-poverty_moe, ymax=mean_poverty+poverty_moe),
                width = .05,
                alpha = .5 ) +
  theme_minimal() #districts with q1 member have higher poverty than everywhere else (1 percentage point), except during great recession.


poverty_plotdat3 <- cel_acs_os %>%
  group_by(congress, q5) %>%
  summarise(mean_poverty = mean(poverty_pct, na.rm = TRUE,),
            poverty_moe = mean(poverty_pct_moe, na.rm = TRUE)) %>%
  mutate(quintile = ifelse(q5==1, "Top 20%", "0-79.9%"))

ggplot(data = poverty_plotdat3, aes(x = congress, y = mean_poverty, color = quintile)) +
  geom_line() +
  geom_errorbar(aes(ymin = mean_poverty-poverty_moe, ymax=mean_poverty+poverty_moe),
                width = .05,
                alpha = .5 ) +
  theme_minimal() #districts with q5 member have lower poverty than everywhere else, especially after the great recession, but most are not significant.




#What about number of wealthy ppl in a district? Check average income to get at extreme outliers and whether there are more super wealthy 

#gini index

cel_acs_os$gini2 <- cel_acs_os$gini*100

summary(lm(gini ~ q1 + q5 + seniority + factor(congress) + deleg_size  + st_name, cel_acs_os)) #not clear, but seniority is associated with greater inequality in districts

summary(lm(q1 ~ gini2 + seniority + factor(congress) + deleg_size + st_name + female, cel_acs_os))# no relationship between gini and q1 

summary(lm(q5 ~ gini2 + seniority + factor(congress) + deleg_size + st_name + female, cel_acs_os)) #no relationship between gini and q5



gini_plotdat3 <- cel_acs_os %>%
  group_by(congress, q5) %>%
  summarise(mean_gini = mean(gini, na.rm = TRUE,),
            gini_moe = mean(gini_moe, na.rm = TRUE)) %>%
  mutate(quintile = ifelse(q5==1, "Top 20%", "0-79.9%"))

ggplot(data = gini_plotdat3, aes(x = congress, y = mean_gini, color = quintile)) +
  geom_line() +
  geom_errorbar(aes(ymin = mean_gini-gini_moe, ymax=mean_gini+gini_moe),
                width = .05,
                alpha = .5 ) +
  theme_minimal()
```
```{r, les robustness check}
#Robustness check on LES models?
summary(lm(les ~ q1 + q5 + log(cd_median_income)  + seniority + sensq + state_leg + state_leg_prof + majority + maj_leader + min_leader + maj_leader + chair + subchr + power + meddist + female + afam + latino  + votepct  +  votepct_sq + deleg_size, cel_acs_os)) #one unit increase in cd median income associated with .35 increase in les.

```

#2  less safety = less effectiveness for poor members

#3  pay increases increase effectiveness 

#4 Political scientists (Davidson et al. 22) says that 1/3 of members were born outside of the state that they were born in. Is this group predominately wealthy because of the mobility that wealth affords?